"""Conteúdo extra dos READMEs de cada tema no GitHub: valores para decorar, glossário, correlações clínicas e onde ler.

EXTRAS[code] = dict(
    essencial=[frases],              # o que não pode faltar na prova
    valores=[(item, valor)],         # tabela de números
    glossario=[(termo, definição)],
    clinica=[(título, texto)],       # correlações clínicas
    leitura=[(trecho da fonte, o que ler)],
)
"""

EXTRAS = {
    "a": dict(
        essencial=[
            "O coração são duas bombas em série; o miocárdio é um sincício funcional graças aos discos intercalares (junções comunicantes).",
            "O platô do potencial de ação ventricular vem da entrada lenta de Ca²⁺ (canais tipo L) e da menor saída de K⁺; por isso o miocárdio não tetaniza.",
            "Liberação de Ca²⁺ induzida por Ca²⁺: o Ca²⁺ que entra pelo túbulo T abre os receptores de rianodina do retículo.",
            "Ciclo cardíaco: contração isovolumétrica → ejeção → relaxamento isovolumétrico → enchimento (rápido, diástase, sístole atrial).",
            "Frank-Starling: quanto mais o ventrículo enche, mais forte contrai; o coração bombeia o que recebe.",
        ],
        valores=[
            ("Potencial de repouso ventricular", "−85 a −90 mV"),
            ("Duração do potencial de ação ventricular", "≈ 0,2 a 0,3 s"),
            ("Período refratário absoluto · relativo (ventrículo)", "0,25 a 0,30 s · + 0,05 s"),
            ("Velocidade de condução: músculo · Purkinje", "0,3 a 0,5 m/s · até 4 m/s"),
            ("Duração do ciclo a 72 bpm", "0,833 s (sístole ≈ 40%)"),
            ("Volume diastólico final · sistólico final", "110 a 120 mℓ · 40 a 50 mℓ"),
            ("Volume sistólico · fração de ejeção", "≈ 70 mℓ · ≈ 60%"),
            ("Pressão no VE: sistólica · diastólica", "≈ 120 mmHg · 0 a 5 mmHg"),
            ("Abertura da valva aórtica", "PVE > 80 mmHg"),
            ("Contribuição da sístole atrial ao enchimento", "≈ 20%"),
            ("Débito cardíaco de repouso · exercício", "4 a 6 ℓ/min · 4 a 7× maior"),
            ("Eficiência máxima do coração", "20 a 25%"),
        ],
        glossario=[
            ("Sincício funcional", "Conjunto de células que se comporta como uma só, porque o potencial passa livremente pelas junções comunicantes."),
            ("Discos intercalares", "Membranas que separam as células do miocárdio; contêm as junções comunicantes (gap junctions)."),
            ("Platô", "Fase 2 do potencial de ação ventricular, sustentada pela entrada de Ca²⁺."),
            ("SERCA2", "Bomba de Ca²⁺ do retículo sarcoplasmático; recapta o Ca²⁺ no relaxamento."),
            ("Pré-carga", "Grau de estiramento do músculo antes de contrair; na prática, a pressão diastólica final."),
            ("Pós-carga", "Carga contra a qual o músculo contrai; na prática, a pressão na aorta."),
            ("Incisura", "Pequena queda na curva da pressão aórtica quando a valva aórtica fecha."),
            ("Trabalho sistólico externo", "Área da alça pressão-volume; energia que o ventrículo transfere ao sangue."),
            ("Diástase", "Fase média da diástole, de enchimento lento."),
        ],
        clinica=[
            ("Hiperpotassemia", "K⁺ alto despolariza o repouso, deixa o coração dilatado e flácido e pode causar bloqueio AV e parada (8 a 12 mEq/ℓ)."),
            ("Hipercalcemia e hipocalcemia", "Ca²⁺ alto leva à contração espástica; Ca²⁺ baixo, a fraqueza do miocárdio."),
            ("Febre", "Aumenta a frequência cardíaca (pode dobrar); a hipotermia a reduz muito."),
            ("Ruptura de músculo papilar", "No infarto, o papilar lesado deixa a cúspide abaular para o átrio: insuficiência mitral aguda."),
            ("Hipertensão e hipertrofia concêntrica", "Pela lei de Laplace, a pressão alta crônica engrossa a parede e reduz o raio para normalizar a tensão."),
        ],
        leitura=[
            ("Guyton cap. 9", "Fisiologia do músculo cardíaco, ciclo cardíaco (Fig. 9.8), alça pressão-volume (Figs. 9.10 e 9.11), Frank-Starling."),
            ("Guyton cap. 23", "Valvas e bulhas cardíacas; áreas de ausculta (Fig. 23.2)."),
            ("Porto, Semiologia Médica", "Exame do coração: focos de ausculta e bulhas."),
        ],
    ),
    "b": dict(
        essencial=[
            "O nó sinusal é o marca-passo porque tem a maior frequência intrínseca (70 a 80/min), graças ao vazamento de Na⁺ pela corrente funny.",
            "O nó AV atrasa o impulso (≈ 0,13 s no total) para os átrios esvaziarem antes de os ventrículos contraírem.",
            "As fibras de Purkinje conduzem muito rápido (1,5 a 4 m/s), fazendo os ventrículos contraírem quase ao mesmo tempo.",
            "Vago: acetilcolina abre canais de K⁺, hiperpolariza e reduz a frequência; simpático: noradrenalina (β1) aumenta Na⁺ e Ca²⁺ e acelera.",
        ],
        valores=[
            ("Repouso do nó sinusal", "−55 a −60 mV"),
            ("Limiar de descarga do nó sinusal", "≈ −40 mV"),
            ("Frequência intrínseca: nó SA · nó AV · Purkinje", "70 a 80 · 40 a 60 · 15 a 40 /min"),
            ("Chegada ao nó AV", "0,03 s"),
            ("Atraso total no nó AV + feixe penetrante", "≈ 0,13 s (chega ao ventrículo em 0,16 s)"),
            ("Velocidade nas vias internodais", "≈ 1 m/s"),
            ("Velocidade no Purkinje", "1,5 a 4 m/s"),
            ("Tempo do feixe até a última fibra ventricular", "≈ 0,06 s"),
            ("Escape ventricular após parada sinusal (Stokes-Adams)", "5 a 20 s de pausa; depois 15 a 40 bpm"),
        ],
        glossario=[
            ("Corrente funny (If)", "Entrada de Na⁺ por canais ativados na hiperpolarização; gera a despolarização lenta do nó sinusal."),
            ("Marca-passo ectópico", "Outro local que passa a disparar mais rápido que o nó sinusal."),
            ("Feixe AV (His)", "Única via elétrica normal entre átrios e ventrículos, através do esqueleto fibroso."),
            ("Síndrome de Stokes-Adams", "Desmaio por pausa ventricular no início de um bloqueio AV total, até o Purkinje assumir."),
            ("Supressão por sobrecarga", "O Purkinje estimulado rápido pelo sinusal fica suprimido e demora a assumir o ritmo."),
            ("Vias internodais", "Feixes anterior, médio e posterior que levam o impulso do nó sinusal ao nó AV."),
        ],
        clinica=[
            ("Bloqueio AV total", "Átrios seguem o sinusal e ventrículos o Purkinje (15 a 40 bpm): bradicardia grave, pode exigir marca-passo."),
            ("Reentrada e via acessória", "Uma via fora do feixe AV pode reconduzir o impulso e causar taquiarritmias (ex.: pré-excitação)."),
            ("Estímulo vagal forte", "Massagem do seio carotídeo ou reflexo vagal intenso pode parar o sinusal por alguns segundos até o escape."),
        ],
        leitura=[
            ("Guyton cap. 10", "Sistema excitocondutor (Fig. 10.1), potencial do nó sinusal (Fig. 10.2), nó AV (Fig. 10.3), tempos de condução (Fig. 10.4)."),
            ("Guyton cap. 9", "Inervação autonômica do coração (Fig. 9.14)."),
        ],
    ),
    "c": dict(
        essencial=[
            "P = despolarização atrial; QRS = despolarização ventricular; T = repolarização ventricular.",
            "Papel padrão: 25 mm/s e 10 mm/mV; quadradinho = 0,04 s e 0,1 mV; quadrado grande = 0,20 s.",
            "Lei de Einthoven: a qualquer instante, I + III = II.",
            "Eixo médio normal do QRS ≈ +59° (Guyton); I e aVF positivos indicam eixo normal na prática.",
        ],
        valores=[
            ("Intervalo PR", "≈ 0,16 s (0,12 a 0,20 s)"),
            ("Duração do QRS", "0,06 a 0,08 s (≥ 0,12 s: bloqueio de ramo)"),
            ("Intervalo QT", "≈ 0,35 s"),
            ("Voltagem do QRS nas derivações dos membros", "1,0 a 1,5 mV"),
            ("Voltagem de P · T", "0,1 a 0,3 mV · 0,2 a 0,3 mV"),
            ("Frequência cardíaca", "60 / RR (s) · 1.500 / quadradinhos · 300 / quadrados grandes"),
            ("Eixos: I · II · III", "0° · +60° · +120°"),
            ("Eixos: aVR · aVL · aVF", "−150° · −30° · +90°"),
            ("Resistências do terminal central (Wilson)", "5.000 Ω em cada membro"),
        ],
        glossario=[
            ("Derivação bipolar", "Registra a diferença entre dois membros (I, II e III)."),
            ("Derivação aumentada", "Um membro contra os outros dois ligados (aVR, aVL, aVF)."),
            ("Precordial", "Eletrodo explorador no tórax (V1 a V6) contra o terminal central."),
            ("Triângulo de Einthoven", "Triângulo formado por braços e perna esquerda em torno do coração."),
            ("Sistema hexaxial", "As seis derivações dos membros desenhadas passando pelo mesmo centro, a cada 30°."),
            ("Segmento ST", "Trecho entre o fim do QRS e o início de T; normalmente na linha de base."),
            ("Progressão de R", "A onda R cresce de V1 para V5 e a S diminui."),
        ],
        clinica=[
            ("Desvio do eixo para a esquerda", "Expiração, deitar, obesidade, hipertrofia do VE ou bloqueio do ramo esquerdo."),
            ("Desvio do eixo para a direita", "Inspiração, ficar em pé, biótipo alto e magro, hipertrofia do VD ou bloqueio do ramo direito."),
            ("Holter e monitor de eventos", "Holter 24 a 48 h para sintomas frequentes; monitor de eventos e loop implantável para sintomas raros ou síncope."),
        ],
        leitura=[
            ("Guyton cap. 11", "ECG normal (Fig. 11.1), Einthoven (Fig. 11.6), precordiais (Figs. 11.8 e 11.9), 12 derivações (Fig. 11.11)."),
            ("Guyton cap. 12", "Vetores e eixo: sistema hexaxial (Fig. 12.3) e cálculo do eixo (Fig. 12.11)."),
        ],
    ),
    "d": dict(
        essencial=[
            "Lei de Ohm: F = ΔP / R. Poiseuille: o fluxo varia com a 4ª potência do raio.",
            "84% do sangue está na circulação sistêmica e 64% nas veias: elas são o reservatório.",
            "As arteríolas fazem ≈ 2/3 da resistência e controlam o fluxo de cada tecido.",
            "Complacência venosa ≈ 24× a arterial. Pressão de pulso ≈ volume sistólico / complacência arterial.",
            "Em pé e imóvel, a pressão nas veias dos pés chega a +90 mmHg; a bomba muscular a reduz para < 20 mmHg.",
        ],
        valores=[
            ("Distribuição do volume: veias · artérias · coração · pulmão", "64% · 13% · 7% · 9%"),
            ("Pressão aórtica · média", "120/80 · ≈ 100 mmHg"),
            ("Pressão capilar sistêmica", "35 → 10 mmHg (funcional ≈ 17)"),
            ("Pressão na artéria pulmonar · capilar pulmonar", "25/8 (média 16) · ≈ 7 mmHg"),
            ("Pressão no átrio direito (PVC)", "≈ 0 mmHg"),
            ("Velocidade na aorta · capilares", "≈ 33 cm/s · ≈ 0,3 mm/s"),
            ("Resistência periférica total · pulmonar", "≈ 1 URP · ≈ 0,14 URP"),
            ("Viscosidade do sangue (água = 1)", "3 a 4 (hematócrito ≈ 40)"),
            ("Pressão de pulso", "≈ 40 mmHg"),
            ("PAM (estimativa clínica)", "PAD + PP/3"),
            ("Pressão hidrostática", "1 mmHg a cada 13,6 mm de sangue"),
            ("Pressão nas veias do pé em pé, imóvel", "+90 mmHg"),
            ("Número de Reynolds para turbulência", "> 200 a 400 nos ramos; > 2.000 em vaso reto"),
        ],
        glossario=[
            ("Condutância", "Inverso da resistência; proporcional à 4ª potência do raio."),
            ("Complacência (capacitância)", "Volume acumulado por mmHg de aumento de pressão (ΔV/ΔP)."),
            ("Distensibilidade", "Aumento fracional do volume por mmHg (ΔV / ΔP × V inicial)."),
            ("Complacência tardia", "Estresse-relaxamento: depois de um aumento de volume, a pressão cai lentamente em minutos a horas."),
            ("Pressão crítica de fechamento", "Pressão abaixo da qual um vaso colapsa e o fluxo para (≈ 20 mmHg)."),
            ("Fluxo laminar", "Camadas concêntricas com perfil parabólico; silencioso."),
            ("Sons de Korotkoff", "Sons do fluxo turbulento sob o manguito; 1º som = sistólica, desaparecimento = diastólica."),
            ("Lei de Laplace", "T = P × r; vasos maiores suportam mais tensão na parede."),
        ],
        clinica=[
            ("Arteriosclerose", "Artérias rígidas: pressão de pulso alta e sistólica alta no idoso."),
            ("Estenose aórtica", "Pressão de pulso pequena e pulso fraco, porque pouco sangue passa pela valva estreitada."),
            ("Insuficiência aórtica e persistência do canal arterial", "Diastólica cai muito e a pressão de pulso aumenta."),
            ("Varizes", "Válvulas venosas incompetentes anulam a bomba muscular: edema e úlcera nas pernas."),
            ("Policitemia e anemia", "Hematócrito 60 a 70 aumenta a viscosidade até 10×; na anemia, viscosidade baixa ajuda a aumentar o débito."),
        ],
        leitura=[
            ("Guyton cap. 14", "Volumes (Fig. 14.1), pressões (Fig. 14.2), Poiseuille (Fig. 14.8), fluxo laminar (Fig. 14.6), viscosidade (Fig. 14.11)."),
            ("Guyton cap. 15", "Complacência (Fig. 15.1), pulso arterial (Figs. 15.3 e 15.4), Korotkoff (Fig. 15.7), gravidade e veias (Fig. 15.10)."),
        ],
    ),
    "e": dict(
        essencial=[
            "A difusão é o principal meio de troca; lipossolúveis cruzam toda a membrana, hidrossolúveis passam pelas fendas intercelulares.",
            "Forças de Starling: Pc e Πi empurram para fora; Πp puxa para dentro; Pi é negativa e também favorece a saída.",
            "Quase todo o filtrado é reabsorvido; o pequeno excesso (≈ 2 mℓ/min) volta pela linfa.",
            "Os linfáticos devolvem as proteínas ao sangue e mantêm a pressão intersticial negativa.",
        ],
        valores=[
            ("Número de capilares · área total", "≈ 10 bilhões · 500 a 700 m²"),
            ("Fenda intercelular", "6 a 7 nm"),
            ("Pressão capilar arterial · venosa · funcional", "30 · 10 · ≈ 17 mmHg"),
            ("Pressão intersticial (subcutâneo)", "≈ −3 mmHg"),
            ("Pressão oncótica do plasma", "28 mmHg (19 proteína + 9 efeito Donnan)"),
            ("Pressão oncótica intersticial", "8 mmHg"),
            ("Pressão efetiva média de filtração", "≈ 0,3 mmHg → ≈ 2 mℓ/min"),
            ("Coeficiente de filtração do corpo", "≈ 6,67 mℓ/min/mmHg"),
            ("Fluxo de linfa", "≈ 120 mℓ/h · 2 a 3 ℓ/dia"),
            ("Proteína na linfa do fígado", "≈ 6 g/dℓ"),
        ],
        glossario=[
            ("Metarteríola", "Ramo terminal da arteríola com músculo liso intermitente."),
            ("Esfíncter pré-capilar", "Anel de músculo liso na origem do capilar; abre e fecha o fluxo."),
            ("Vasomotricidade", "Abertura e fechamento intermitente dos capilares, regulada sobretudo pelo O₂."),
            ("Cavéolas", "Vesículas da membrana endotelial que fazem a transcitose de macromoléculas."),
            ("Gel tecidual", "Líquido intersticial preso entre os proteoglicanos."),
            ("Efeito Donnan", "Cátions retidos pelas proteínas negativas do plasma que somam pressão oncótica."),
            ("Filamentos de ancoragem", "Prendem o capilar linfático ao tecido e o abrem quando o interstício incha."),
            ("Bomba linfática", "Contração dos segmentos linfáticos entre válvulas, somada à compressão externa."),
        ],
        clinica=[
            ("Insuficiência cardíaca", "↑ Pressão venosa → ↑ Pc → filtração maior que a capacidade linfática → edema."),
            ("Cirrose e síndrome nefrótica", "↓ Albumina → ↓ Πp → edema e ascite."),
            ("Queimadura e inflamação", "↑ Permeabilidade capilar: proteína sai, ↑ Πi e edema."),
            ("Linfedema", "Obstrução linfática (filariose, câncer, retirada de linfonodos): proteína acumula no interstício."),
        ],
        leitura=[
            ("Guyton cap. 16", "Microcirculação (Fig. 16.1), parede capilar (Fig. 16.2), interstício (Fig. 16.4), forças de Starling (Fig. 16.5), linfáticos (Figs. 16.6 a 16.8)."),
        ],
    ),
    "f": dict(
        essencial=[
            "Cada tecido controla o próprio fluxo pelo metabolismo (adenosina, CO₂, K⁺, H⁺, falta de O₂).",
            "Autorregulação: de 70 a 175 mmHg o fluxo muda pouco (mecanismos metabólico e miogênico).",
            "NO: cisalhamento → eNOS → guanilato ciclase solúvel → GMPc → relaxamento.",
            "Barorreflexo: controle rápido da PA (seio carotídeo → IX; arco aórtico → X; ambos ao NTS), mas se reajusta em 1 a 2 dias.",
            "Resposta isquêmica do SNC (PA < 60) é o último recurso; a reação de Cushing é sua forma clínica.",
        ],
        valores=[
            ("Fração do DC: fígado · rins · músculo · cérebro · coração", "27 · 22 · 15 · 14 · 4%"),
            ("Fluxo renal por 100 g", "≈ 360 mℓ/min"),
            ("Hiperemia reativa", "fluxo 4 a 7×"),
            ("Faixa de autorregulação aguda", "70 a 175 mmHg"),
            ("Tônus vasoconstritor simpático", "0,5 a 2 impulsos/s"),
            ("Raquianestesia total", "PA 100 → 50 mmHg"),
            ("Barorreceptor carotídeo: limiar · máximo · maior ganho", "50 a 60 · ≈ 180 · ≈ 100 mmHg"),
            ("Reajuste dos barorreceptores", "1 a 2 dias"),
            ("Quimiorreceptores atuam abaixo de", "80 mmHg"),
            ("Resposta isquêmica do SNC", "PA < 60 mmHg; PA pode ir a 250"),
            ("Reflexo de Bainbridge", "FC ↑ 40 a 60%"),
            ("Ondas de Mayer", "10 a 40 mmHg, a cada 7 a 10 s"),
        ],
        glossario=[
            ("Hiperemia ativa", "Aumento do fluxo quando o metabolismo do tecido sobe."),
            ("Hiperemia reativa", "Aumento do fluxo após um período de oclusão."),
            ("Autorregulação miogênica", "Estiramento do vaso → entrada de Ca²⁺ → contração."),
            ("Feedback tubuloglomerular", "A mácula densa ajusta a arteríola aferente conforme o líquido tubular."),
            ("Angiogênese", "Crescimento de novos vasos, estimulado por VEGF (via HIF) quando falta O₂."),
            ("Remodelagem eutrófica", "Muda a luz do vaso sem mudar a área da parede."),
            ("Centro vasomotor", "Áreas do bulbo e da ponte que controlam o simpático e o vago."),
            ("Núcleo do trato solitário", "Área sensorial do bulbo que recebe barorreceptores e quimiorreceptores."),
        ],
        clinica=[
            ("Síncope vasovagal", "Emoção → vasodilatação muscular + bradicardia vagal → PA cai → desmaio."),
            ("Reação de Cushing", "Hipertensão intracraniana → isquemia do centro vasomotor → PA alta com bradicardia."),
            ("Apneia do sono e obesidade", "Hipóxia repetida ativa quimiorreceptores e o simpático: contribui para hipertensão."),
            ("Nitratos e sildenafila", "Nitratos doam NO (angina); sildenafila inibe a PDE-5 (disfunção erétil). Juntos causam hipotensão grave."),
            ("Hipertensão pulmonar", "Tratada com bloqueadores dos receptores de endotelina."),
        ],
        leitura=[
            ("Guyton cap. 17", "Controle metabólico (Figs. 17.1 a 17.3), hiperemia (Fig. 17.4), autorregulação (Fig. 17.5), NO (Fig. 17.6), remodelagem (Fig. 17.8)."),
            ("Guyton cap. 18", "Centro vasomotor (Fig. 18.3), raquianestesia (Fig. 18.4), barorreceptores (Figs. 18.5 a 18.9), reflexos atriais (Fig. 18.10)."),
        ],
    ),
}
